import type { Metadata } from "next";
// import "../globals.css";
import Navbar from "@/components/admin/NavBar";
import SideBar from "@/components/admin/SideBar";

export const metadata: Metadata = {
  title: "Afflaite Farm App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="min-h-screen grid grid-rows-[auto,1fr] grid-cols-[250px,1fr]">
          <div className="row-span-1 col-span-1">
            <SideBar />
          </div>
          <div className="row-span-1 col-span-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
