import Head from "next/head";
import dynamic from "next/dynamic";
import SideNav from "../SideBar";
import type { Metadata } from "next";
import Footer from "../Footer";

const Navbar = dynamic(() => import("../NavBar"), { ssr: false });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AffiliatePageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>HI</title>
      </Head>
      <body>
        <div className="hide-scrollbar w-full">
          <Navbar />

          <div className="min-h-screen max-container w-full lg:grid-cols-[250px,1fr] grid ">
            <div className="row-span-1 col-span-1 hidden lg:block ">
              <SideNav />
            </div>
            <div className="row-span-1 col-span-1 ">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
