
// lib/data.ts
export const programData = [
    {
        src: "/jasper.svg",
        commission: "$400.00",
        name: "Jasper AI",
        productDescription: "Content writing tool",
        payout: "$100 Payout",
        cookie: "60 days cookie",
        promoted: true,
        programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
        adsOn: true,
        programIDIcon: true, 
        programID: 'Program ID: 00480', 
        url: '/', 
        verifiedIconSrc: "/verified.svg",
        linkName: "Join Program",
        verified:true,
    },
    {
      src: "/jasper.svg",
      commission: "$400.00",
      name: "Jasper AI",
      productDescription: "Content writing tool",
      payout: "$100 Payout",
      cookie: "60 days cookie",
      promoted: true,
      programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
      adsOn: true,
      programIDIcon: true, 
      programID: 'Program ID: 00480', 
      url: '/', 
      verifiedIconSrc: "/verified.svg",
      linkName: "Join Program",
      verified:true,
  },
  {
    src: "/jasper.svg",
    commission: "$400.00",
    name: "Jasper AI",
    productDescription: "Content writing tool",
    payout: "$100 Payout",
    cookie: "60 days cookie",
    promoted: true,
    programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    adsOn: true,
    programIDIcon: true, 
    programID: 'Program ID: 00480', 
    url: '/', 
    verifiedIconSrc: "/verified.svg",
    linkName: "Join Program",
    verified:false,
},
{
  src: "/jasper.svg",
  commission: "$400.00",
  name: "Jasper AI",
  productDescription: "Content writing tool",
  payout: "$100 Payout",
  cookie: "60 days cookie",
  promoted: false,
  programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
  adsOn: true,
  programIDIcon: true, 
  programID: 'Program ID: 00480', 
  url: '/', 
  verifiedIconSrc: "/verified.svg",
  linkName: "Join Program",
  verified:false,
},
{
  src: "/jasper.svg",
  commission: "$400.00",
  name: "Jasper AI",
  productDescription: "Content writing tool",
  payout: "$100 Payout",
  cookie: "60 days cookie",
  promoted: false,
  programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
  adsOn: true,
  programIDIcon: true, 
  programID: 'Program ID: 00480', 
  url: '/', 
  verifiedIconSrc: "/verified.svg",
  linkName: "Join Program",
  verified:false,
},
{
  src: "/jasper.svg",
  commission: "$400.00",
  name: "Jasper AI",
  productDescription: "Content writing tool",
  payout: "$100 Payout",
  cookie: "60 days cookie",
  promoted: false,
  programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
  adsOn: true,
  programIDIcon: true, 
  programID: 'Program ID: 00480', 
  url: '/', 
  verifiedIconSrc: "/verified.svg",
  linkName: "Join Program",
  verified:true,
},
{
  src: "/jasper.svg",
  commission: "$400.00",
  name: "Jasper AI",
  productDescription: "Content writing tool",
  payout: "$100 Payout",
  cookie: "60 days cookie",
  promoted: false,
  programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
  adsOn: true,
  programIDIcon: true, 
  programID: 'Program ID: 00480', 
  url: '/', 
  verifiedIconSrc: "/verified.svg",
  linkName: "Join Program",
  verified:false,
},
{
  src: "/jasper.svg",
  commission: "$400.00",
  name: "Jasper AI",
  productDescription: "Content writing tool",
  payout: "$100 Payout",
  cookie: "60 days cookie",
  promoted: false,
  programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
  adsOn: false,
  programIDIcon: true, 
  programID: 'Program ID: 00480', 
  url: '/', 
  verifiedIconSrc: "/verified.svg",
  linkName: "Join Program",
  verified: true,
},
{
  src: "/jasper.svg",
  commission: "$400.00",
  name: "Jasper AI",
  productDescription: "Content writing tool",
  payout: "$100 Payout",
  cookie: "60 days cookie",
  promoted: false,
  programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
  adsOn: false,
  programIDIcon: true, 
  programID: 'Program ID: 00480', 
  url: '/', 
  verifiedIconSrc: "/verified.svg",
  linkName: "Join Program",
  verified:false,
},
{
  src: "/jasper.svg",
  commission: "$400.00",
  name: "Jasper AI",
  productDescription: "Content writing tool",
  payout: "$100 Payout",
  cookie: "60 days cookie",
  promoted: false,
  programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
  adsOn: false,
  programIDIcon: true, 
  programID: 'Program ID: 00480', 
  url: '/', 
  verifiedIconSrc: "/verified.svg",
  linkName: "Join Program",
  verified:false,
},
{
  src: "/jasper.svg",
  commission: "$400.00",
  name: "Jasper AI",
  productDescription: "Content writing tool",
  payout: "$100 Payout",
  cookie: "60 days cookie",
  promoted: false,
  programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
  adsOn: true,
  programIDIcon: true, 
  programID: 'Program ID: 00480', 
  url: '/', 
  verifiedIconSrc: "/verified.svg",
  linkName: "Join Program",
  verified:false,
},
{
  src: "/jasper.svg",
  commission: "$400.00",
  name: "Jasper AI",
  productDescription: "Content writing tool",
  payout: "$100 Payout",
  cookie: "60 days cookie",
  promoted: false,
  programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
  adsOn: true,
  programIDIcon: true, 
  programID: 'Program ID: 00480', 
  url: '/', 
  verifiedIconSrc: "/verified.svg",
  linkName: "Join Program",
  verified:false,
},
{
  src: "/jasper.svg",
  commission: "$400.00",
  name: "Jasper AI",
  productDescription: "Content writing tool",
  payout: "$100 Payout",
  cookie: "60 days cookie",
  promoted: false,
  programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
  adsOn: false,
  programIDIcon: true, 
  programID: 'Program ID: 00480', 
  url: '/', 
  verifiedIconSrc: "/verified.svg",
  linkName: "Join Program",
  verified:false,
},
{
  src: "/jasper.svg",
  commission: "$400.00",
  name: "Jasper AI",
  productDescription: "Content writing tool",
  payout: "$100 Payout",
  cookie: "60 days cookie",
  promoted: false,
  programDescription: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
  adsOn: false,
  programIDIcon: true, 
  programID: 'Program ID: 00480', 
  url: '/', 
  verifiedIconSrc: "/verified.svg",
  linkName: "Join Program",
  verified:false,
},

  ];
  
  export async function fetchPrograms(offset: number, limit: number, query: string = '') {
  
    return new Promise<typeof programData>(resolve => {
      setTimeout(() => {
        const filteredData = programData.filter(program =>
          program.name.toLowerCase().includes(query.toLowerCase()) ||
          program.productDescription.toLowerCase().includes(query.toLowerCase()) ||
          program.cookie.toLowerCase().includes(query.toLowerCase()) ||
          program.payout.toLowerCase().includes(query.toLowerCase()) ||
          program.commission.toLowerCase().includes(query.toLowerCase()) ||
          program.programID.toLowerCase().includes(query.toLowerCase()) 
        );
        resolve(filteredData.slice(offset, offset + limit));
      }, 500);
    });
  }
  