

// lib/data.ts
export const programData = [
  {
    id: 1,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-001",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: true,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "$",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: true,
    linkName: "Join Program"
  },
  {
    id: 2,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-002",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: true,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "$",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: true,
    linkName: "Join Program"
  },
  {
    id: 3,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-003",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: false,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "$",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: true,
    linkName: "Join Program"
  },
  {
    id: 4,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-004",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: false,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "$",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: false,
    linkName: "Join Program"
  },
  {
    id: 5,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-005",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: false,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "$",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: false,
    linkName: "Join Program"
  },
  {
    id: 6,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-006",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: true,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "$",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: false,
    linkName: "Join Program"
  },
  {
    id: 7,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-007",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: false,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "$",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: false,
    linkName: "Join Program"
  },
  {
    id: 8,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-008",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: true,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "$",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: false,
    linkName: "Join Program"
  },
  {
    id: 9,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-009",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: false,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "$",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: false,
    linkName: "Join Program"
  },
  {
    id: 10,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-010",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: false,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "USD",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: true,
    linkName: "Join Program"
  },
  {
    id: 11,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-011",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: false,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "USD",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: true,
    linkName: "Join Program"
  },
  {
    id: 12,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-012",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: false,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "USD",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: false,
    linkName: "Join Program"
  },
  {
    id: 13,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-013",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: false,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "USD",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: false,
    linkName: "Join Program"
  },
  {
    id: 14,
    niche: 1,
    niche_details: { /* insert appropriate NicheDetails structure here */ },
    logo: "/jasper.svg",
    code: "PRG-014",
    name: "Jasper AI",
    publisherName: "Jasper Inc.",
    publisherEmail: "contact@jasper.ai",
    programUrl: "/",
    shortDescription: "Content writing tool",
    description: "With jasper user can start creating massive blog, ebook, music, etc contents with AI.",
    cookieDuration: 60,
    cookieExpires: false,
    commissionRate: 400.00,
    payoutAmount: 100.00,
    verified: false,
    affiliateType: "Type A",
    affiliateLevel: "Level 1",
    paymentMethod: "Bank Transfer",
    currency: "USD",
    commissionType: "Flat",
    ticketType: "Support",
    created_at: "2024-07-14T00:00:00Z",
    updated_at: "2024-07-14T00:00:00Z",
    promoted: false,
    linkName: "Join Program"
  }
];

  
  export async function fetchPrograms(offset: number, limit: number, query: string = '') {
  
    return new Promise<typeof programData>(resolve => {
      setTimeout(() => {
        const filteredData = programData.filter(program =>
          program.name.toLowerCase().includes(query.toLowerCase()) ||
          program.description.toLowerCase().includes(query.toLowerCase()) ||
          program.cookieDuration.toString().includes(query) ||
          program.payoutAmount.toString().includes(query) ||
          program.commissionRate.toString().includes(query) ||
          program.id.toString().includes(query)
        );
        resolve(filteredData.slice(offset, offset + limit));
      }, 500);
    });
  }
  