import type { Metadata } from "next";
// import "../globals.css";
import Navbar from "@/components/admin/NavBar";

export const metadata: Metadata = {
  title: "Afflaite Farm App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
